//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.pmp.web.sms {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", ConfigurationName="sms.SDKClient")]
    public interface SDKClient {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        com.pmp.web.sms.getVersionResponse getVersion(com.pmp.web.sms.getVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.pmp.web.sms.getVersionResponse> getVersionAsync(com.pmp.web.sms.getVersionRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        com.pmp.web.sms.getReportResponse getReport(com.pmp.web.sms.getReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.pmp.web.sms.getReportResponse> getReportAsync(com.pmp.web.sms.getReportRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        com.pmp.web.sms.cancelMOForwardResponse cancelMOForward(com.pmp.web.sms.cancelMOForwardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.pmp.web.sms.cancelMOForwardResponse> cancelMOForwardAsync(com.pmp.web.sms.cancelMOForwardRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        com.pmp.web.sms.chargeUpResponse chargeUp(com.pmp.web.sms.chargeUpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.pmp.web.sms.chargeUpResponse> chargeUpAsync(com.pmp.web.sms.chargeUpRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        com.pmp.web.sms.getBalanceResponse getBalance(com.pmp.web.sms.getBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.pmp.web.sms.getBalanceResponse> getBalanceAsync(com.pmp.web.sms.getBalanceRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        com.pmp.web.sms.getEachFeeResponse getEachFee(com.pmp.web.sms.getEachFeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.pmp.web.sms.getEachFeeResponse> getEachFeeAsync(com.pmp.web.sms.getEachFeeRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        com.pmp.web.sms.getMOResponse getMO(com.pmp.web.sms.getMORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.pmp.web.sms.getMOResponse> getMOAsync(com.pmp.web.sms.getMORequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        com.pmp.web.sms.logoutResponse logout(com.pmp.web.sms.logoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.pmp.web.sms.logoutResponse> logoutAsync(com.pmp.web.sms.logoutRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        com.pmp.web.sms.registDetailInfoResponse registDetailInfo(com.pmp.web.sms.registDetailInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.pmp.web.sms.registDetailInfoResponse> registDetailInfoAsync(com.pmp.web.sms.registDetailInfoRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        com.pmp.web.sms.registExResponse registEx(com.pmp.web.sms.registExRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.pmp.web.sms.registExResponse> registExAsync(com.pmp.web.sms.registExRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        com.pmp.web.sms.sendSMSResponse sendSMS(com.pmp.web.sms.sendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.pmp.web.sms.sendSMSResponse> sendSMSAsync(com.pmp.web.sms.sendSMSRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        com.pmp.web.sms.sendVoiceResponse sendVoice(com.pmp.web.sms.sendVoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.pmp.web.sms.sendVoiceResponse> sendVoiceAsync(com.pmp.web.sms.sendVoiceRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        com.pmp.web.sms.serialPwdUpdResponse serialPwdUpd(com.pmp.web.sms.serialPwdUpdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.pmp.web.sms.serialPwdUpdResponse> serialPwdUpdAsync(com.pmp.web.sms.serialPwdUpdRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        com.pmp.web.sms.setMOForwardResponse setMOForward(com.pmp.web.sms.setMOForwardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.pmp.web.sms.setMOForwardResponse> setMOForwardAsync(com.pmp.web.sms.setMOForwardRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        com.pmp.web.sms.setMOForwardExResponse setMOForwardEx(com.pmp.web.sms.setMOForwardExRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<com.pmp.web.sms.setMOForwardExResponse> setMOForwardExAsync(com.pmp.web.sms.setMOForwardExRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersion", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getVersionRequest {
        
        public getVersionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersionResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getVersionResponse() {
        }
        
        public getVersionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/")]
    public partial class statusReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string memoField;
        
        private string mobileField;
        
        private string receiveDateField;
        
        private int reportStatusField;
        
        private long seqIDField;
        
        private string serviceCodeAddField;
        
        private string submitDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string receiveDate {
            get {
                return this.receiveDateField;
            }
            set {
                this.receiveDateField = value;
                this.RaisePropertyChanged("receiveDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int reportStatus {
            get {
                return this.reportStatusField;
            }
            set {
                this.reportStatusField = value;
                this.RaisePropertyChanged("reportStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long seqID {
            get {
                return this.seqIDField;
            }
            set {
                this.seqIDField = value;
                this.RaisePropertyChanged("seqID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string serviceCodeAdd {
            get {
                return this.serviceCodeAddField;
            }
            set {
                this.serviceCodeAddField = value;
                this.RaisePropertyChanged("serviceCodeAdd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string submitDate {
            get {
                return this.submitDateField;
            }
            set {
                this.submitDateField = value;
                this.RaisePropertyChanged("submitDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/")]
    public partial class mo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addSerialField;
        
        private string addSerialRevField;
        
        private string channelnumberField;
        
        private string mobileNumberField;
        
        private string sentTimeField;
        
        private string smsContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string addSerial {
            get {
                return this.addSerialField;
            }
            set {
                this.addSerialField = value;
                this.RaisePropertyChanged("addSerial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string addSerialRev {
            get {
                return this.addSerialRevField;
            }
            set {
                this.addSerialRevField = value;
                this.RaisePropertyChanged("addSerialRev");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string channelnumber {
            get {
                return this.channelnumberField;
            }
            set {
                this.channelnumberField = value;
                this.RaisePropertyChanged("channelnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string mobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                this.mobileNumberField = value;
                this.RaisePropertyChanged("mobileNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string sentTime {
            get {
                return this.sentTimeField;
            }
            set {
                this.sentTimeField = value;
                this.RaisePropertyChanged("sentTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string smsContent {
            get {
                return this.smsContentField;
            }
            set {
                this.smsContentField = value;
                this.RaisePropertyChanged("smsContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReport", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getReportRequest() {
        }
        
        public getReportRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReportResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public com.pmp.web.sms.statusReport[] @return;
        
        public getReportResponse() {
        }
        
        public getReportResponse(com.pmp.web.sms.statusReport[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelMOForward", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class cancelMOForwardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public cancelMOForwardRequest() {
        }
        
        public cancelMOForwardRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelMOForwardResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class cancelMOForwardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public cancelMOForwardResponse() {
        }
        
        public cancelMOForwardResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="chargeUp", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class chargeUpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        public chargeUpRequest() {
        }
        
        public chargeUpRequest(string arg0, string arg1, string arg2, string arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="chargeUpResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class chargeUpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public chargeUpResponse() {
        }
        
        public chargeUpResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBalance", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getBalanceRequest() {
        }
        
        public getBalanceRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBalanceResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public getBalanceResponse() {
        }
        
        public getBalanceResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEachFee", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getEachFeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getEachFeeRequest() {
        }
        
        public getEachFeeRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEachFeeResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getEachFeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public getEachFeeResponse() {
        }
        
        public getEachFeeResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMO", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getMORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getMORequest() {
        }
        
        public getMORequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMOResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class getMOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public com.pmp.web.sms.mo[] @return;
        
        public getMOResponse() {
        }
        
        public getMOResponse(com.pmp.web.sms.mo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logout", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class logoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public logoutRequest() {
        }
        
        public logoutRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logoutResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class logoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public logoutResponse() {
        }
        
        public logoutResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registDetailInfo", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class registDetailInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg8;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg9;
        
        public registDetailInfoRequest() {
        }
        
        public registDetailInfoRequest(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, string arg8, string arg9) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
            this.arg9 = arg9;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registDetailInfoResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class registDetailInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public registDetailInfoResponse() {
        }
        
        public registDetailInfoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registEx", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class registExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public registExRequest() {
        }
        
        public registExRequest(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registExResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class registExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public registExResponse() {
        }
        
        public registExResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMS", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class sendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("arg3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg8;
        
        public sendSMSRequest() {
        }
        
        public sendSMSRequest(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class sendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public sendSMSResponse() {
        }
        
        public sendSMSResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendVoice", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class sendVoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("arg3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg8;
        
        public sendVoiceRequest() {
        }
        
        public sendVoiceRequest(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendVoiceResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class sendVoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sendVoiceResponse() {
        }
        
        public sendVoiceResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="serialPwdUpd", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class serialPwdUpdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        public serialPwdUpdRequest() {
        }
        
        public serialPwdUpdRequest(string arg0, string arg1, string arg2, string arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="serialPwdUpdResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class serialPwdUpdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public serialPwdUpdResponse() {
        }
        
        public serialPwdUpdResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMOForward", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class setMOForwardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public setMOForwardRequest() {
        }
        
        public setMOForwardRequest(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMOForwardResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class setMOForwardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public setMOForwardResponse() {
        }
        
        public setMOForwardResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMOForwardEx", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class setMOForwardExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("arg2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] arg2;
        
        public setMOForwardExRequest() {
        }
        
        public setMOForwardExRequest(string arg0, string arg1, string[] arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setMOForwardExResponse", WrapperNamespace="http://sdkhttp.eucp.b2m.cn/", IsWrapped=true)]
    public partial class setMOForwardExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdkhttp.eucp.b2m.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public setMOForwardExResponse() {
        }
        
        public setMOForwardExResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SDKClientChannel : com.pmp.web.sms.SDKClient, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SDKClientClient : System.ServiceModel.ClientBase<com.pmp.web.sms.SDKClient>, com.pmp.web.sms.SDKClient {
        
        public SDKClientClient() {
        }
        
        public SDKClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SDKClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SDKClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SDKClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.pmp.web.sms.getVersionResponse com.pmp.web.sms.SDKClient.getVersion(com.pmp.web.sms.getVersionRequest request) {
            return base.Channel.getVersion(request);
        }
        
        public string getVersion() {
            com.pmp.web.sms.getVersionRequest inValue = new com.pmp.web.sms.getVersionRequest();
            com.pmp.web.sms.getVersionResponse retVal = ((com.pmp.web.sms.SDKClient)(this)).getVersion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.pmp.web.sms.getVersionResponse> com.pmp.web.sms.SDKClient.getVersionAsync(com.pmp.web.sms.getVersionRequest request) {
            return base.Channel.getVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.pmp.web.sms.getVersionResponse> getVersionAsync() {
            com.pmp.web.sms.getVersionRequest inValue = new com.pmp.web.sms.getVersionRequest();
            return ((com.pmp.web.sms.SDKClient)(this)).getVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.pmp.web.sms.getReportResponse com.pmp.web.sms.SDKClient.getReport(com.pmp.web.sms.getReportRequest request) {
            return base.Channel.getReport(request);
        }
        
        public com.pmp.web.sms.statusReport[] getReport(string arg0, string arg1) {
            com.pmp.web.sms.getReportRequest inValue = new com.pmp.web.sms.getReportRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            com.pmp.web.sms.getReportResponse retVal = ((com.pmp.web.sms.SDKClient)(this)).getReport(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.pmp.web.sms.getReportResponse> com.pmp.web.sms.SDKClient.getReportAsync(com.pmp.web.sms.getReportRequest request) {
            return base.Channel.getReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.pmp.web.sms.getReportResponse> getReportAsync(string arg0, string arg1) {
            com.pmp.web.sms.getReportRequest inValue = new com.pmp.web.sms.getReportRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((com.pmp.web.sms.SDKClient)(this)).getReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.pmp.web.sms.cancelMOForwardResponse com.pmp.web.sms.SDKClient.cancelMOForward(com.pmp.web.sms.cancelMOForwardRequest request) {
            return base.Channel.cancelMOForward(request);
        }
        
        public int cancelMOForward(string arg0, string arg1) {
            com.pmp.web.sms.cancelMOForwardRequest inValue = new com.pmp.web.sms.cancelMOForwardRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            com.pmp.web.sms.cancelMOForwardResponse retVal = ((com.pmp.web.sms.SDKClient)(this)).cancelMOForward(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.pmp.web.sms.cancelMOForwardResponse> com.pmp.web.sms.SDKClient.cancelMOForwardAsync(com.pmp.web.sms.cancelMOForwardRequest request) {
            return base.Channel.cancelMOForwardAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.pmp.web.sms.cancelMOForwardResponse> cancelMOForwardAsync(string arg0, string arg1) {
            com.pmp.web.sms.cancelMOForwardRequest inValue = new com.pmp.web.sms.cancelMOForwardRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((com.pmp.web.sms.SDKClient)(this)).cancelMOForwardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.pmp.web.sms.chargeUpResponse com.pmp.web.sms.SDKClient.chargeUp(com.pmp.web.sms.chargeUpRequest request) {
            return base.Channel.chargeUp(request);
        }
        
        public int chargeUp(string arg0, string arg1, string arg2, string arg3) {
            com.pmp.web.sms.chargeUpRequest inValue = new com.pmp.web.sms.chargeUpRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            com.pmp.web.sms.chargeUpResponse retVal = ((com.pmp.web.sms.SDKClient)(this)).chargeUp(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.pmp.web.sms.chargeUpResponse> com.pmp.web.sms.SDKClient.chargeUpAsync(com.pmp.web.sms.chargeUpRequest request) {
            return base.Channel.chargeUpAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.pmp.web.sms.chargeUpResponse> chargeUpAsync(string arg0, string arg1, string arg2, string arg3) {
            com.pmp.web.sms.chargeUpRequest inValue = new com.pmp.web.sms.chargeUpRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((com.pmp.web.sms.SDKClient)(this)).chargeUpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.pmp.web.sms.getBalanceResponse com.pmp.web.sms.SDKClient.getBalance(com.pmp.web.sms.getBalanceRequest request) {
            return base.Channel.getBalance(request);
        }
        
        public double getBalance(string arg0, string arg1) {
            com.pmp.web.sms.getBalanceRequest inValue = new com.pmp.web.sms.getBalanceRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            com.pmp.web.sms.getBalanceResponse retVal = ((com.pmp.web.sms.SDKClient)(this)).getBalance(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.pmp.web.sms.getBalanceResponse> com.pmp.web.sms.SDKClient.getBalanceAsync(com.pmp.web.sms.getBalanceRequest request) {
            return base.Channel.getBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.pmp.web.sms.getBalanceResponse> getBalanceAsync(string arg0, string arg1) {
            com.pmp.web.sms.getBalanceRequest inValue = new com.pmp.web.sms.getBalanceRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((com.pmp.web.sms.SDKClient)(this)).getBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.pmp.web.sms.getEachFeeResponse com.pmp.web.sms.SDKClient.getEachFee(com.pmp.web.sms.getEachFeeRequest request) {
            return base.Channel.getEachFee(request);
        }
        
        public double getEachFee(string arg0, string arg1) {
            com.pmp.web.sms.getEachFeeRequest inValue = new com.pmp.web.sms.getEachFeeRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            com.pmp.web.sms.getEachFeeResponse retVal = ((com.pmp.web.sms.SDKClient)(this)).getEachFee(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.pmp.web.sms.getEachFeeResponse> com.pmp.web.sms.SDKClient.getEachFeeAsync(com.pmp.web.sms.getEachFeeRequest request) {
            return base.Channel.getEachFeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.pmp.web.sms.getEachFeeResponse> getEachFeeAsync(string arg0, string arg1) {
            com.pmp.web.sms.getEachFeeRequest inValue = new com.pmp.web.sms.getEachFeeRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((com.pmp.web.sms.SDKClient)(this)).getEachFeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.pmp.web.sms.getMOResponse com.pmp.web.sms.SDKClient.getMO(com.pmp.web.sms.getMORequest request) {
            return base.Channel.getMO(request);
        }
        
        public com.pmp.web.sms.mo[] getMO(string arg0, string arg1) {
            com.pmp.web.sms.getMORequest inValue = new com.pmp.web.sms.getMORequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            com.pmp.web.sms.getMOResponse retVal = ((com.pmp.web.sms.SDKClient)(this)).getMO(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.pmp.web.sms.getMOResponse> com.pmp.web.sms.SDKClient.getMOAsync(com.pmp.web.sms.getMORequest request) {
            return base.Channel.getMOAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.pmp.web.sms.getMOResponse> getMOAsync(string arg0, string arg1) {
            com.pmp.web.sms.getMORequest inValue = new com.pmp.web.sms.getMORequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((com.pmp.web.sms.SDKClient)(this)).getMOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.pmp.web.sms.logoutResponse com.pmp.web.sms.SDKClient.logout(com.pmp.web.sms.logoutRequest request) {
            return base.Channel.logout(request);
        }
        
        public int logout(string arg0, string arg1) {
            com.pmp.web.sms.logoutRequest inValue = new com.pmp.web.sms.logoutRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            com.pmp.web.sms.logoutResponse retVal = ((com.pmp.web.sms.SDKClient)(this)).logout(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.pmp.web.sms.logoutResponse> com.pmp.web.sms.SDKClient.logoutAsync(com.pmp.web.sms.logoutRequest request) {
            return base.Channel.logoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.pmp.web.sms.logoutResponse> logoutAsync(string arg0, string arg1) {
            com.pmp.web.sms.logoutRequest inValue = new com.pmp.web.sms.logoutRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((com.pmp.web.sms.SDKClient)(this)).logoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.pmp.web.sms.registDetailInfoResponse com.pmp.web.sms.SDKClient.registDetailInfo(com.pmp.web.sms.registDetailInfoRequest request) {
            return base.Channel.registDetailInfo(request);
        }
        
        public int registDetailInfo(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, string arg8, string arg9) {
            com.pmp.web.sms.registDetailInfoRequest inValue = new com.pmp.web.sms.registDetailInfoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            inValue.arg9 = arg9;
            com.pmp.web.sms.registDetailInfoResponse retVal = ((com.pmp.web.sms.SDKClient)(this)).registDetailInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.pmp.web.sms.registDetailInfoResponse> com.pmp.web.sms.SDKClient.registDetailInfoAsync(com.pmp.web.sms.registDetailInfoRequest request) {
            return base.Channel.registDetailInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.pmp.web.sms.registDetailInfoResponse> registDetailInfoAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, string arg8, string arg9) {
            com.pmp.web.sms.registDetailInfoRequest inValue = new com.pmp.web.sms.registDetailInfoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            inValue.arg9 = arg9;
            return ((com.pmp.web.sms.SDKClient)(this)).registDetailInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.pmp.web.sms.registExResponse com.pmp.web.sms.SDKClient.registEx(com.pmp.web.sms.registExRequest request) {
            return base.Channel.registEx(request);
        }
        
        public int registEx(string arg0, string arg1, string arg2) {
            com.pmp.web.sms.registExRequest inValue = new com.pmp.web.sms.registExRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            com.pmp.web.sms.registExResponse retVal = ((com.pmp.web.sms.SDKClient)(this)).registEx(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.pmp.web.sms.registExResponse> com.pmp.web.sms.SDKClient.registExAsync(com.pmp.web.sms.registExRequest request) {
            return base.Channel.registExAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.pmp.web.sms.registExResponse> registExAsync(string arg0, string arg1, string arg2) {
            com.pmp.web.sms.registExRequest inValue = new com.pmp.web.sms.registExRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((com.pmp.web.sms.SDKClient)(this)).registExAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.pmp.web.sms.sendSMSResponse com.pmp.web.sms.SDKClient.sendSMS(com.pmp.web.sms.sendSMSRequest request) {
            return base.Channel.sendSMS(request);
        }
        
        public int sendSMS(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            com.pmp.web.sms.sendSMSRequest inValue = new com.pmp.web.sms.sendSMSRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            com.pmp.web.sms.sendSMSResponse retVal = ((com.pmp.web.sms.SDKClient)(this)).sendSMS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.pmp.web.sms.sendSMSResponse> com.pmp.web.sms.SDKClient.sendSMSAsync(com.pmp.web.sms.sendSMSRequest request) {
            return base.Channel.sendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.pmp.web.sms.sendSMSResponse> sendSMSAsync(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            com.pmp.web.sms.sendSMSRequest inValue = new com.pmp.web.sms.sendSMSRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            return ((com.pmp.web.sms.SDKClient)(this)).sendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.pmp.web.sms.sendVoiceResponse com.pmp.web.sms.SDKClient.sendVoice(com.pmp.web.sms.sendVoiceRequest request) {
            return base.Channel.sendVoice(request);
        }
        
        public string sendVoice(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            com.pmp.web.sms.sendVoiceRequest inValue = new com.pmp.web.sms.sendVoiceRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            com.pmp.web.sms.sendVoiceResponse retVal = ((com.pmp.web.sms.SDKClient)(this)).sendVoice(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.pmp.web.sms.sendVoiceResponse> com.pmp.web.sms.SDKClient.sendVoiceAsync(com.pmp.web.sms.sendVoiceRequest request) {
            return base.Channel.sendVoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.pmp.web.sms.sendVoiceResponse> sendVoiceAsync(string arg0, string arg1, string arg2, string[] arg3, string arg4, string arg5, string arg6, int arg7, long arg8) {
            com.pmp.web.sms.sendVoiceRequest inValue = new com.pmp.web.sms.sendVoiceRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            return ((com.pmp.web.sms.SDKClient)(this)).sendVoiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.pmp.web.sms.serialPwdUpdResponse com.pmp.web.sms.SDKClient.serialPwdUpd(com.pmp.web.sms.serialPwdUpdRequest request) {
            return base.Channel.serialPwdUpd(request);
        }
        
        public int serialPwdUpd(string arg0, string arg1, string arg2, string arg3) {
            com.pmp.web.sms.serialPwdUpdRequest inValue = new com.pmp.web.sms.serialPwdUpdRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            com.pmp.web.sms.serialPwdUpdResponse retVal = ((com.pmp.web.sms.SDKClient)(this)).serialPwdUpd(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.pmp.web.sms.serialPwdUpdResponse> com.pmp.web.sms.SDKClient.serialPwdUpdAsync(com.pmp.web.sms.serialPwdUpdRequest request) {
            return base.Channel.serialPwdUpdAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.pmp.web.sms.serialPwdUpdResponse> serialPwdUpdAsync(string arg0, string arg1, string arg2, string arg3) {
            com.pmp.web.sms.serialPwdUpdRequest inValue = new com.pmp.web.sms.serialPwdUpdRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((com.pmp.web.sms.SDKClient)(this)).serialPwdUpdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.pmp.web.sms.setMOForwardResponse com.pmp.web.sms.SDKClient.setMOForward(com.pmp.web.sms.setMOForwardRequest request) {
            return base.Channel.setMOForward(request);
        }
        
        public int setMOForward(string arg0, string arg1, string arg2) {
            com.pmp.web.sms.setMOForwardRequest inValue = new com.pmp.web.sms.setMOForwardRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            com.pmp.web.sms.setMOForwardResponse retVal = ((com.pmp.web.sms.SDKClient)(this)).setMOForward(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.pmp.web.sms.setMOForwardResponse> com.pmp.web.sms.SDKClient.setMOForwardAsync(com.pmp.web.sms.setMOForwardRequest request) {
            return base.Channel.setMOForwardAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.pmp.web.sms.setMOForwardResponse> setMOForwardAsync(string arg0, string arg1, string arg2) {
            com.pmp.web.sms.setMOForwardRequest inValue = new com.pmp.web.sms.setMOForwardRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((com.pmp.web.sms.SDKClient)(this)).setMOForwardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.pmp.web.sms.setMOForwardExResponse com.pmp.web.sms.SDKClient.setMOForwardEx(com.pmp.web.sms.setMOForwardExRequest request) {
            return base.Channel.setMOForwardEx(request);
        }
        
        public int setMOForwardEx(string arg0, string arg1, string[] arg2) {
            com.pmp.web.sms.setMOForwardExRequest inValue = new com.pmp.web.sms.setMOForwardExRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            com.pmp.web.sms.setMOForwardExResponse retVal = ((com.pmp.web.sms.SDKClient)(this)).setMOForwardEx(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.pmp.web.sms.setMOForwardExResponse> com.pmp.web.sms.SDKClient.setMOForwardExAsync(com.pmp.web.sms.setMOForwardExRequest request) {
            return base.Channel.setMOForwardExAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.pmp.web.sms.setMOForwardExResponse> setMOForwardExAsync(string arg0, string arg1, string[] arg2) {
            com.pmp.web.sms.setMOForwardExRequest inValue = new com.pmp.web.sms.setMOForwardExRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((com.pmp.web.sms.SDKClient)(this)).setMOForwardExAsync(inValue);
        }
    }
}
